image: ubuntu:18.04
stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip python3
    - pip3 install flask
    - cd src
    - python3 -m unittest multiplytest